capture:
  name: Capture
  description: Captures the current states of entities in the specified scene and persists them to scenes.yaml.
  target:
    entity:
      domain: scene # Restricts to scene entities
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID of the scene to capture (e.g., scene.adjustable_living_room).
      required: true
      example: "scene.adjustable_living_room"
      selector:
        entity:
          domain: scene
