capture:
  name: Capture
  description: Captures the current states of entities in the specified scene and persists them to scenes.yaml.
  target:
    entity:
      domain: scene
      multiple: false
